nav:
  - Home: README.md
  - Management: management
  - Methods: methods
  - Data: data
  - Analysis: analysis
  - Figures: figures
  - Dissemination: dissemination
  - Miscellaneous: misc
  - API: api

sort:
  type: natural
  ignore_case: true
  by: title
  direction: asc
flatten_single_child_sections: true

