{% raw %}# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: "3.11"

      - name: Build environment
        run: make environment

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy docs
        run: conda run -n{% endraw %}{{ cookiecutter.project_name }}-dev{% raw %} mkdocs gh-deploy --force
